### ISSUE TITLE
A problem about the RBM based recommendation

### ISSUE THREAD

**Issue by ylfzr** [saurabhmathur96/movie-recommendations#2]
In your implementation of RBM based CF, I see you directly fed the rating data in, ratings ranges from 1-5. I think this should corresponds to Guassian visible layer because the data is not binary, which is different from the original implementation of Ruslan and Hinton.  However, your reconstruction, v_2 seems to be binary...  

This confused me because I think in RBM, v_2 should try to reconstruct the input data, so I don't know why real input but binary reconstruction works. Can you give some explanation about this?

**Comment by saurabhmathur96** [comment]
I actually used a modified version of their model. The output of the RBM is a probability distribution of how much a user will like the movie. To make a prediction, I rescaled the probabilities from [0,1] to [0,5]
